name: Daily Stock Alert

on:
  schedule:
    - cron: "0 13 * * 1-5" # 15:00 Prague (30 min before US market opens)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock analysis and send email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python analyze.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main  # avoid conflicts
          git add rsi_state.json rsi_buy_signals.json
          git commit -m "Update RSI state and buy signals from GitHub Action" || echo "No changes to commit"
          git push origin main
