name: Daily Stock Alert

on:
  schedule:
    - cron: "0 6 * * 1-5"
    - cron: "0 19 * * 1-5"
  workflow_dispatch:

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy python-dotenv

      - name: Run stock analysis and send email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python analyze.py
