name: Daily Stock Alert

on:
  schedule:
    - cron: "30 13 * * 1-5" # Runs 8:30 AM UTC = 4:30 AM ET (before market)
    - cron: "30 21 * * 1-5" # Runs 5:30 PM UTC = 1:30 PM ET (after close)
  workflow_dispatch:

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance pandas numpy python-dotenv

      - name: Run stock analysis and send email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python analyze.py
