name: Daily Tradinng Bot

on:
  schedule:
    - cron: "31 13 * * 1-5" # 15:31 Prague (1 min after US market opens)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock trading bot
        env:
          API_KEY_PAPER: ${{ secrets.API_KEY_PAPER }}
          BASE_URL_PAPER: ${{ secrets.BASE_URL_PAPER }}
          SECRET_KEY_PAPER: ${{ secrets.SECRET_KEY_PAPER }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python bot.py

      - name: Commit and push updated positions.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin master  # avoid conflicts
          git add positions.csv
          git commit -m "Update positions.csv from GitHub Action" || echo "No changes to commit"
          git push origin master
